---
name: Lingua-CollinsParser
version: 0.05
author:
  - 'Ken Williams, ken.williams@thomson.com'
abstract: Head-driven syntactic sentence parser
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  XML::Generator: 0
build_requires:
  Module::Build: 0.21
  Test::More: 0
provides:
  Lingua::CollinsParser:
    file: lib/Lingua/CollinsParser.pm
    version: 0.05
  Lingua::CollinsParser::Node:
    file: lib/Lingua/CollinsParser/Node.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
